version: "3.10"

services:
  web_office:
    container_name: web_office
    build:
      context: ./
    volumes:
      - ./app/:/home/mikita/Documents/PycharmProjects/office/src
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
    command: >
      sh -c "python ./src/manage.py makemigrations && 
             python ./src/manage.py migrate &&
             python ./src/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db_office

  db_office:
    image: postgres:14.5-alpine
    container_name: db_office
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=officeuser
      - POSTGRES_PASSWORD=officeuser123
      - POSTGRES_DB=office
    ports:
      - "5432:5432"

volumes:
  postgres_data: