# Generated by Django 4.1.3 on 2022-11-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='rest',
        ),
        migrations.AddField(
            model_name='myuser',
            name='rest',
            field=models.ManyToManyField(related_name='user_rest', to='main.rest'),
        ),
    ]
